# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efd5ee6d824db7af9a336e2bbeea218e1c38b1599065f4076d6b19c28445bf74b52a27c46f081eafbd3a2075ee79b7b35655685c4425dfa3945ba010bebe8c26

test:
  secret_key_base: 5f74817a01df9bf68c92150fd764d7c847d925ab2eb55637ea87d97791ad4058d2f89aaf599734e59f3ff6aaa6c9dcffc536973dab7549981ec6b6eead30c001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
